### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by Lzrnk** [nafdev01/django_pkms#1]
When I try to open http://127.0.0.1:8000
I get Server Error (500)
Nothing wrong in console
```
System check identified no issues (0 silenced).
February 03, 2024 - 22:25:42
Django version 4.1.7, using settings 'django_pkms.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Feb/2024 22:25:51] "GET / HTTP/1.1" 500 145

```

**Comment by nafdev01** [comment]
set debug to True in your environment variables and restart the server again for more a more detailed error message which will be easier to debug
